/**
 * Storybook 문서와 reference 스토리에서 사용하는 예제 코드 문자열 모음입니다.
 */

export const editorPackageUsageSnippet = [
  "import 'chaeditor/styles.css';",
  '',
  "import { MarkdownEditor } from 'chaeditor/react';",
  '',
  "import { uploadEditorFile, uploadEditorImage, uploadEditorVideo } from 'chaeditor/default-host';",
  '',
  'const Example = () => {',
  "  const [value, setValue] = useState('# Hello chaeditor');",
  '',
  '  return (',
  '    <MarkdownEditor',
  '      adapters={{',
  '        uploadFile: uploadEditorFile,',
  '        uploadImage: uploadEditorImage,',
  '        uploadVideo: uploadEditorVideo,',
  '      }}',
  '      contentType="article"',
  '      onChange={setValue}',
  '      value={value}',
  '    />',
  '  );',
  '};',
].join('\n');

export const toolbarPackageUsageSnippet = [
  "import 'chaeditor/styles.css';",
  '',
  "import { MarkdownToolbar } from 'chaeditor/react';",
  '',
  'const Example = () => {',
  '  const textareaRef = useRef<HTMLTextAreaElement | null>(null);',
  "  const [value, setValue] = useState('');",
  '',
  '  return (',
  '    <>',
  '      <MarkdownToolbar',
  '        contentType="article"',
  '        onChange={setValue}',
  '        textareaRef={textareaRef}',
  '      />',
  '      <textarea ref={textareaRef} value={value} onChange={event => setValue(event.target.value)} />',
  '    </>',
  '  );',
  '};',
].join('\n');

export const rendererPackageUsageSnippet = [
  "import 'chaeditor/styles.css';",
  '',
  "import { MarkdownRenderer } from 'chaeditor/react';",
  '',
  'const Example = async () => {',
  "  return <MarkdownRenderer markdown={'# Hello chaeditor'} />;",
  '};',
].join('\n');

export const customAdapterUsageSnippet = [
  "import 'chaeditor/styles.css';",
  '',
  "import { MarkdownEditor } from 'chaeditor/react';",
  '',
  'const adapters = {',
  '  fetchLinkPreviewMeta: async url => ({',
  "    title: 'Custom host preview',",
  "    description: 'Injected by the host app',",
  '    url,',
  '  }),',
  '  renderImage: ({ alt, className, src }) => (',
  "    <img alt={alt} className={className} src={typeof src === 'string' ? src : src.src} />",
  '  ),',
  '};',
  '',
  'const Example = () => (',
  '  <MarkdownEditor',
  '    adapters={adapters}',
  '    contentType="article"',
  '    onChange={() => {}}',
  '    value=""',
  '  />',
  ');',
].join('\n');

export const themeOverrideUsageSnippet = [
  "import 'chaeditor/styles.css';",
  '',
  "import { createChaeditorThemeVars } from 'chaeditor/core';",
  "import { MarkdownEditor } from 'chaeditor/react';",
  '',
  'const themeVars = createChaeditorThemeVars({',
  "  primary: '#0f766e',",
  "  primarySubtle: '#ccfbf1',",
  "  surface: '#f8fafc',",
  "  surfaceMuted: '#ecfeff',",
  "  text: '#0f172a',",
  "  textSubtle: '#475569',",
  "  sansFont: 'var(--app-font-sans), system-ui, sans-serif',",
  '  monoFont: "var(--font-d2coding), \'D2Coding\', monospace",',
  '});',
  '',
  'const Example = () => (',
  '  <div style={themeVars}>',
  '    <MarkdownEditor contentType="article" onChange={() => {}} value="" />',
  '  </div>',
  ');',
].join('\n');

export const primitiveRegistryUsageSnippet = [
  "import 'chaeditor/styles.css';",
  '',
  "import { MarkdownEditor, Popover, Tooltip } from 'chaeditor/react';",
  '',
  'const HostButton = props => (',
  "  <button {...props} className={`host-button ${props.className ?? ''}`.trim()} />",
  ');',
  '',
  'const HostPopover = ({ viewportPadding = 12, ...props }) => (',
  '  <Popover',
  '    {...props}',
  '    viewportPadding={viewportPadding}',
  "    panelClassName={`host-popover-panel ${props.panelClassName ?? ''}`.trim()}",
  "    triggerClassName={`host-popover-trigger ${props.triggerClassName ?? ''}`.trim()}",
  '  />',
  ');',
  '',
  'const HostTooltip = ({ viewportPadding = 10, ...props }) => (',
  '  <Tooltip',
  '    {...props}',
  "    preferredPlacement={props.preferredPlacement ?? 'auto'}",
  '    viewportPadding={viewportPadding}',
  "    contentClassName={`host-tooltip ${props.contentClassName ?? ''}`.trim()}",
  '  />',
  ');',
  '',
  'const Example = () => (',
  '  <MarkdownEditor',
  '    contentType="article"',
  '    onChange={() => {}}',
  '    primitiveRegistry={{',
  '      Button: HostButton,',
  '      Input: HostInput,',
  '      Textarea: HostTextarea,',
  '      Popover: HostPopover,',
  '      Modal: HostModal,',
  '      Tooltip: HostTooltip,',
  '    }}',
  '    value=""',
  '  />',
  ');',
].join('\n');

export const tailwindThemeUsageSnippet = [
  "import 'chaeditor/styles.css';",
  '',
  "import { MarkdownEditor } from 'chaeditor/react';",
  '',
  'const Example = () => (',
  '  <div',
  '    className=[',
  "      '[--chaeditor-color-primary:#0f766e]',",
  "      '[--chaeditor-color-primary-subtle:#ccfbf1]',",
  "      '[--chaeditor-color-surface:#f8fafc]',",
  "      '[--chaeditor-color-text:#0f172a]',",
  "      '[--chaeditor-font-sans:var(--app-font-sans),system-ui,sans-serif]',",
  "      '[--chaeditor-font-mono:var(--font-d2coding),D2Coding,monospace]',",
  "    ].join(' ')",
  '  >',
  '    <MarkdownEditor contentType="article" onChange={() => {}} value="" />',
  '  </div>',
  ');',
].join('\n');

export const tailwindPrimitiveUsageSnippet = [
  "import 'chaeditor/styles.css';",
  '',
  "import { Button, Input, MarkdownEditor, Modal, Popover, Textarea, Tooltip } from 'chaeditor/react';",
  '',
  'const HostButton = props => (',
  '  <Button',
  '    {...props}',
  "    className={`rounded-xl border border-teal-700 bg-teal-50 font-semibold text-teal-900 ${props.className ?? ''}`.trim()}",
  '  />',
  ');',
  '',
  'const HostInput = props => (',
  '  <Input',
  '    {...props}',
  "    className={`rounded-xl border border-teal-700 bg-cyan-50 ${props.className ?? ''}`.trim()}",
  '  />',
  ');',
  '',
  'const HostModal = props => (',
  '  <Modal',
  '    {...props}',
  "    frameClassName={`rounded-3xl border border-teal-700 bg-white shadow-xl ${props.frameClassName ?? ''}`.trim()}",
  "    backdropClassName={`bg-slate-950/55 ${props.backdropClassName ?? ''}`.trim()}",
  '  />',
  ');',
  '',
  'const Example = () => (',
  '  <div',
  '    className=[',
  "      '[--chaeditor-color-primary:#0f766e]',",
  "      '[--chaeditor-color-surface:#f8fafc]',",
  "      '[--chaeditor-color-text:#0f172a]',",
  "    ].join(' ')",
  '  >',
  '    <MarkdownEditor',
  '      contentType="article"',
  '      onChange={() => {}}',
  '      primitiveRegistry={{',
  '        Button: HostButton,',
  '        Input: HostInput,',
  '        Textarea: Textarea,',
  '        Popover: Popover,',
  '        Modal: HostModal,',
  '        Tooltip: Tooltip,',
  '      }}',
  '      value=""',
  '    />',
  '  </div>',
  ');',
].join('\n');

export const emotionThemeUsageSnippet = [
  "import 'chaeditor/styles.css';",
  '',
  "import { css } from '@emotion/react';",
  "import { createChaeditorThemeVars } from 'chaeditor/core';",
  "import { MarkdownEditor } from 'chaeditor/react';",
  '',
  'const editorTheme = css({',
  '  ...createChaeditorThemeVars({',
  "    primary: '#0f766e',",
  "    surface: '#f8fafc',",
  "    text: '#0f172a',",
  "    sansFont: 'var(--app-font-sans), system-ui, sans-serif',",
  '  }),',
  '});',
  '',
  'const Example = () => (',
  '  <div css={editorTheme}>',
  '    <MarkdownEditor contentType="article" onChange={() => {}} value="" />',
  '  </div>',
  ');',
].join('\n');

export const emotionPrimitiveUsageSnippet = [
  "import 'chaeditor/styles.css';",
  '',
  "import { css } from '@emotion/react';",
  "import { Button, Input, MarkdownEditor, Modal, Popover, Textarea, Tooltip } from 'chaeditor/react';",
  "import { createChaeditorThemeVars } from 'chaeditor/core';",
  '',
  'const themeScope = css({',
  '  ...createChaeditorThemeVars({',
  "    primary: '#0f766e',",
  "    surface: '#f8fafc',",
  "    text: '#0f172a',",
  '  }),',
  '});',
  '',
  "const hostButton = css({ borderColor: '#0f766e', borderRadius: 20, background: '#ccfbf1' });",
  "const hostInput = css({ borderColor: '#0f766e', borderRadius: 20, background: '#ecfeff' });",
  '',
  'const HostButton = props => <Button {...props} className={hostButton} />;',
  'const HostInput = props => <Input {...props} className={hostInput} />;',
  '',
  'const HostModal = props => (',
  '  <Modal',
  '    {...props}',
  "    frameClassName={css({ borderColor: '#0f766e', borderRadius: 28, background: '#fff' })}",
  "    backdropClassName={css({ background: 'rgba(15,23,42,0.55)' })}",
  '  />',
  ');',
  '',
  'const Example = () => (',
  '  <div css={themeScope}>',
  '    <MarkdownEditor',
  '      contentType="article"',
  '      onChange={() => {}}',
  '      primitiveRegistry={{',
  '        Button: HostButton,',
  '        Input: HostInput,',
  '        Textarea: Textarea,',
  '        Popover: Popover,',
  '        Modal: HostModal,',
  '        Tooltip: Tooltip,',
  '      }}',
  '      value=""',
  '    />',
  '  </div>',
  ');',
].join('\n');

export const styledComponentsThemeUsageSnippet = [
  "import 'chaeditor/styles.css';",
  '',
  "import styled from 'styled-components';",
  "import { createChaeditorThemeVars } from 'chaeditor/core';",
  "import { MarkdownEditor } from 'chaeditor/react';",
  '',
  'const EditorThemeScope = styled.div(createChaeditorThemeVars({',
  "  primary: '#0f766e',",
  "  surface: '#f8fafc',",
  "  text: '#0f172a',",
  "  sansFont: 'var(--app-font-sans), system-ui, sans-serif',",
  '}));',
  '',
  'const Example = () => (',
  '  <EditorThemeScope>',
  '    <MarkdownEditor contentType="article" onChange={() => {}} value="" />',
  '  </EditorThemeScope>',
  ');',
].join('\n');

export const styledComponentsPrimitiveUsageSnippet = [
  "import 'chaeditor/styles.css';",
  '',
  "import styled from 'styled-components';",
  "import { Button, Input, MarkdownEditor, Modal, Popover, Textarea, Tooltip } from 'chaeditor/react';",
  "import { createChaeditorThemeVars } from 'chaeditor/core';",
  '',
  'const EditorThemeScope = styled.div(createChaeditorThemeVars({',
  "  primary: '#0f766e',",
  "  surface: '#f8fafc',",
  "  text: '#0f172a',",
  '}));',
  '',
  'const HostButton = styled(Button)`border-color: #0f766e; border-radius: 20px; background: #ccfbf1;`;',
  'const HostInput = styled(Input)`border-color: #0f766e; border-radius: 20px; background: #ecfeff;`;',
  '',
  'const HostModal = props => (',
  '  <Modal',
  '    {...props}',
  "    frameClassName={`host-modal-frame ${props.frameClassName ?? ''}`.trim()}",
  "    backdropClassName={`host-modal-backdrop ${props.backdropClassName ?? ''}`.trim()}",
  '  />',
  ');',
  '',
  'const Example = () => (',
  '  <EditorThemeScope>',
  '    <MarkdownEditor',
  '      contentType="article"',
  '      onChange={() => {}}',
  '      primitiveRegistry={{',
  '        Button: HostButton,',
  '        Input: HostInput,',
  '        Textarea: Textarea,',
  '        Popover: Popover,',
  '        Modal: HostModal,',
  '        Tooltip: Tooltip,',
  '      }}',
  '      value=""',
  '    />',
  '  </EditorThemeScope>',
  ');',
].join('\n');

export const vanillaExtractThemeUsageSnippet = [
  "import 'chaeditor/styles.css';",
  '',
  "import { createChaeditorThemeVars } from 'chaeditor/core';",
  "import { MarkdownEditor } from 'chaeditor/react';",
  "import { style } from '@vanilla-extract/css';",
  '',
  'const editorThemeScope = style({',
  '  vars: createChaeditorThemeVars({',
  "    primary: '#0f766e',",
  "    surface: '#f8fafc',",
  "    text: '#0f172a',",
  "    sansFont: 'var(--app-font-sans), system-ui, sans-serif',",
  '  }),',
  '});',
  '',
  'const Example = () => (',
  '  <div className={editorThemeScope}>',
  '    <MarkdownEditor contentType="article" onChange={() => {}} value="" />',
  '  </div>',
  ');',
].join('\n');

export const vanillaExtractPrimitiveUsageSnippet = [
  "import 'chaeditor/styles.css';",
  '',
  "import { style } from '@vanilla-extract/css';",
  "import { Button, Input, MarkdownEditor, Modal, Popover, Textarea, Tooltip } from 'chaeditor/react';",
  "import { createChaeditorThemeVars } from 'chaeditor/core';",
  '',
  'const themeScope = style({',
  '  vars: createChaeditorThemeVars({',
  "    primary: '#0f766e',",
  "    surface: '#f8fafc',",
  "    text: '#0f172a',",
  '  }),',
  '});',
  '',
  "const hostButton = style({ borderColor: '#0f766e', borderRadius: 20, background: '#ccfbf1' });",
  "const hostInput = style({ borderColor: '#0f766e', borderRadius: 20, background: '#ecfeff' });",
  "const hostModalFrame = style({ borderColor: '#0f766e', borderRadius: 28, background: '#fff' });",
  '',
  'const HostButton = props => <Button {...props} className={hostButton} />;',
  'const HostInput = props => <Input {...props} className={hostInput} />;',
  'const HostModal = props => <Modal {...props} frameClassName={hostModalFrame} />;',
  '',
  'const Example = () => (',
  '  <div className={themeScope}>',
  '    <MarkdownEditor',
  '      contentType="article"',
  '      onChange={() => {}}',
  '      primitiveRegistry={{',
  '        Button: HostButton,',
  '        Input: HostInput,',
  '        Textarea: Textarea,',
  '        Popover: Popover,',
  '        Modal: HostModal,',
  '        Tooltip: Tooltip,',
  '      }}',
  '      value=""',
  '    />',
  '  </div>',
  ');',
].join('\n');
