import type React from 'react';

import type { EditorContentType } from '@/entities/editor-core/model/content-types';
import type { EditorAttachment } from '@/entities/editor-core/model/editor-attachment';
import type { EditorImageUploadKind } from '@/shared/lib/image/image-upload-kind';
import type { LinkEmbedData } from '@/shared/lib/markdown/link-embed';

export type PreviewImageSource = string | { src: string };

/**
 * Shared image render props passed to a host-provided image renderer.
 */
export type HostImageRenderProps = {
  /** Accessible image alternative text. */
  alt: string;
  /** Optional class name applied by the package surface. */
  className?: string;
  /** Whether the image is expected to fill an absolutely positioned frame. */
  fill?: boolean;
  /** Optional responsive sizes hint forwarded to the host image primitive. */
  sizes?: string;
  /** Source value generated by the editor or renderer. */
  src: PreviewImageSource;
};

/**
 * Renders an image node with a host-specific image primitive.
 *
 * When omitted, the package falls back to its default <img>-based renderer.
 */
export type HostImageRenderer = (props: HostImageRenderProps) => React.ReactNode;

/**
 * Label overrides used by the built-in image viewer UI.
 */
export type MarkdownImageViewerLabels = {
  actionBarAriaLabel: string;
  closeAriaLabel: string;
  fitToScreenAriaLabel: string;
  imageViewerAriaLabel?: string;
  locateSourceAriaLabel: string;
  nextAriaLabel: string;
  openAriaLabel: string;
  previousAriaLabel: string;
  selectForFrameAriaLabel: string;
  selectForFrameLabel: string;
  thumbnailListAriaLabel: string;
  zoomInAriaLabel: string;
  zoomOutAriaLabel: string;
};

/**
 * Uploads an editor image and returns the final public URL.
 *
 * When this adapter is omitted, image upload flows stay available only if the caller
 * injects a different upload implementation through the relevant UI surface.
 */
export type UploadEditorImage = (payload: {
  /** Logical content type that scopes the upload target. */
  contentType: EditorContentType;
  /** Raw browser file selected by the user. */
  file: File;
  /** Upload intent used by the host to optimize the image differently when needed. */
  imageKind: EditorImageUploadKind;
}) => Promise<string>;

/**
 * Uploads an editor attachment and returns the uploaded file metadata.
 *
 * When omitted, attachment upload UI can still render but should disable upload-specific actions.
 */
export type UploadEditorFile = (payload: {
  /** Logical content type that scopes the upload target. */
  contentType: EditorContentType;
  /** Raw browser file selected by the user. */
  file: File;
}) => Promise<EditorAttachment>;

/**
 * Uploads an editor video and returns the final public URL.
 *
 * When omitted, video helpers can fall back to URL-only insertion flows.
 */
export type UploadEditorVideo = (payload: {
  /** Logical content type that scopes the upload target. */
  contentType: EditorContentType;
  /** Raw browser file selected by the user. */
  file: File;
  /** Optional progress callback that receives a 0-100 percentage. */
  onProgress?: (percentage: number) => void;
  /** Optional abort signal for cancelable uploads. */
  signal?: AbortSignal;
}) => Promise<string>;

/**
 * Resolves the final attachment href in the host application.
 *
 * When omitted, the renderer uses the original href from markdown content.
 */
export type ResolveAttachmentHref = (payload: { fileName: string; href: string }) => string | null;

/**
 * Fetches metadata used by link preview cards.
 *
 * When omitted, link preview components fall back to plain link rendering.
 */
export type FetchLinkPreviewMeta = (
  url: string,
  signal?: AbortSignal,
) => Promise<LinkEmbedData | null>;

/**
 * Host-level adapters used by the markdown renderer and related UI.
 */
export type MarkdownRendererHostAdapters = {
  /** Optional metadata fetcher for rich link preview cards. */
  fetchLinkPreviewMeta?: FetchLinkPreviewMeta;
  /** Optional label overrides for the built-in image viewer. */
  imageViewerLabels?: Partial<MarkdownImageViewerLabels>;
  /** Optional image renderer override for framework-specific image primitives. */
  renderImage?: HostImageRenderer;
  /** Optional attachment href resolver. */
  resolveAttachmentHref?: ResolveAttachmentHref;
};

/**
 * Host-level adapters used by the editor toolbar, embed modals, and renderer.
 */
export type MarkdownEditorHostAdapters = MarkdownRendererHostAdapters & {
  /** Optional attachment upload implementation. */
  uploadFile?: UploadEditorFile;
  /** Optional image upload implementation. */
  uploadImage?: UploadEditorImage;
  /** Optional video upload implementation. */
  uploadVideo?: UploadEditorVideo;
};
